# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TCEV Emergency beta
email: jerbau@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  TCEV Emergency aims to provide an efficient way to help
  residents of the community find and contact an appropriate
  government agency during an emergency.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tcev-emergency.onrender.com/" # the base hostname & protocol for your site, e.g. http://example.com
dribbble_username: jerbau
facebook_username: jerbau
flickr_username: jerbau
github_username: jerbau
pinterest_username: jer_bau
mastodon: jerbau
instagram_username: jerbau
linkedin_username: jerbau
twitter_username: jerbau
youtube_username: JeromeBautista

google_analytics: UA-178036965-1

jekyll_get_json:
  - data: tcev
    json: http://localhost:5000/entity

permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
theme: minima
minima:
  skin: dark
  date_format: "%-d%b%Y"
plugins:
  - jekyll-feed
gems:
  - jekyll-font-awesome-sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
